In [ ]:
import scipy.linalg as ln 
import numpy as np
from underthesea import word_tokenize

sentence = 'Tôi học. Tôi chơi' 
token = word_tokenize(sentence)
# Tokenize câu search
print('tokenization of sentences: ', token)

In [24]:
from scipy.sparse import coo_matrix

# Định nghĩa các vị trí có giá trị khác 0
row = [0, 0]  # Hàng 0 có 2 phần tử khác 0
col = [1, 2]  # Các cột tương ứng là 1 và 2
data = [1, 1]  # Giá trị tại các vị trí này là 1

# Tạo ma trận thưa và chuyển sang dạng đầy đủ (dense)
X = coo_matrix((data, (row, col)), shape=(3, 3)).toarray()

X

array([[0, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
# Phân tích SVD
U, S, VT = np.linalg.svd(X)

print("Ma trận U là", U)
print("Ma trận S là", S)
print("Ma trận VT là", VT)

Ma trận U là [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
Ma trận S là [ 1.41421356  0.         -0.        ]
Ma trận VT là [[-0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]
 [-1.         -0.         -0.        ]]


In [26]:
S_truncate = np.zeros(shape = (2, 3))
np.fill_diagonal(S_truncate, S[:2])
print('S truncate: \n', S_truncate)
print('Word Embedding 2 dimensionality: \n', np.dot(S_truncate, VT))

S truncate: 
 [[1.41421356 0.         0.        ]
 [0.         0.         0.        ]]
Word Embedding 2 dimensionality: 
 [[0. 1. 1.]
 [0. 0. 0.]]
